name: Deploy Academic Pages

on:
  push:
    branches:
      - master
      - main  # 确保包含你当前使用的分支名

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Academic Pages 建议使用较稳健的 2.7 或 3.0
          bundler-cache: true

      - name: Build and Deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages' # 建议部署到这个分支